### ISSUE TITLE
Support for `key-id` with `private-key` OAuth2 authentication

### ISSUE THREAD

**Issue by binaek** [turbot/steampipe-plugin-okta#124]
**Is your feature request related to a problem? Please describe.**
Okta requires that there should be a `key-id` with the `private-key` when authenticating with OAuth2.0

**Describe the solution you'd like**
A `KeyId` field in `okta.spc` which is used by the Okta client

**Describe alternatives you've considered**
We can use `token` based authentication.

**Additional context**
1. https://github.com/okta/okta-sdk-golang?tab=readme-ov-file#oauth-20-with-private-key
2. https://pkg.go.dev/github.com/okta/okta-sdk-golang/v2/okta#WithPrivateKeyId

**Comment by misraved** [comment]
Hi @binaek,

I hope all is well with you. I'm writing to follow up on this issue. Since we haven't received any updates or feedback from you on this [Added support for key-id with private-key OAuth2 authentication](https://github.com/turbot/steampipe-plugin-okta/commit/d6652cd5b8aa2cf434f1392d2d69cd3bdcb900c7) PR, we'll be closing this issue for now.

If you still need assistance or if you have any further questions, please feel free to reopen the issue or create a new one. We're always here to help!

Thank you for your understanding.
